### ISSUE TITLE
Touchbar not working after suspend

### ISSUE THREAD

**Issue by MoonPadUSer** [t2linux/T2-Ubuntu#9]
I am on a 15,4 and after being suspended once the touchbar is not working anymore.
The `apple_ib_tb` module still shows up in `lsmod` but it doesn't seem to work

**Comment by marcosfad** [comment]
Hi, 
For that I added this small script:
https://github.com/marcosfad/mbp-ubuntu/blob/master/files/suspend/rmmod_tb.sh
Check out here:
https://github.com/marcosfad/mbp-ubuntu/blob/master/01_build_file_system.sh#L39
It supposed to remove the driver and added later again. 

You may try this manually when the problem come up.

**Comment by reynaldliu** [comment]
mbp 16,1 same

**Comment by tpchuckles** [comment]
Any way to get this to run on lid close? might be a timing issue. (manually clicking "suspend" and then waiting for everything to go dark, then closing the lid, seems to work. just closing the lid means i won't get the touchbar once we're back up)

alternatively, any commands to get the touchbar back once it's gone? ("modprobe -r apple_ic_tb ; modprobe apple_ic_tb" doesn't seem to work. as though crashing the module means we can't restart it or something...)

**Comment by AdityaGarg8** [comment]
Bug has been fixed in the latest kernels

**Comment by lexkyiv** [comment]
@AdityaGarg8 

The bug is still present, and there seems to be no way to fix it. I tried using ChatGPT and multiple different approaches, but the chat ultimately said that this issue is not fixable and no resolution is available. The keyboard backlight and Touch Bar stop working after the system wakes from suspension.

Kernel version: 6.18.1-1-t2-noble
MacBook Pro 2019 A2141

Could you please advise on which kernel version this was fixed in?

This issue makes any setup unusable because the Touch Bar has all the function buttons and you can't access them after closing the lid. The only option is to disable sleep entirely, but then the computer just discharges in your bag. Is any resolution available?

**Comment by AdityaGarg8** [comment]
> [@AdityaGarg8](https://github.com/AdityaGarg8)
> 
> The bug is still present, and there seems to be no way to fix it. I tried using ChatGPT and multiple different approaches, but the chat ultimately said that this issue is not fixable and no resolution is available. The keyboard backlight and Touch Bar stop working after the system wakes from suspension.
> 
> Kernel version: 6.18.1-1-t2-noble MacBook Pro 2019 A2141
> 
> Could you please advise on which kernel version this was fixed in?
> 
> This issue makes any setup unusable because the Touch Bar has all the function buttons and you can't access them after closing the lid. The only option is to disable sleep entirely, but then the computer just discharges in your bag. Is any resolution available?

It has been broken again after an update by Apple to T2's firmware :(

**Comment by AdityaGarg8** [comment]
Are you using tiny-dfr or normal touchbar?

**Comment by lexkyiv** [comment]
> Are you using tiny-dfr or normal touchbar?

I'm not sure, but if I understand right, both are in use:

<img width="2754" height="316" alt="Image" src="https://github.com/user-attachments/assets/eff16cd8-cc3c-40e5-a68a-d0b157a609b3" />

**Comment by AdityaGarg8** [comment]
With tiny-dfr, suspend is anyways broken. Try removing tiny-dfr, restart, then before suspending run `sudo modprobe -r hid-appletb-kbd && sudo modprobe -r hid-appletb-bl` and after resume run `sudo modprobe hid-appletb-bl && sudo modprobe hid-appletb-kbd`. Tell me if this works or not.

**Comment by jondkelley** [comment]
Any updates? Is anyone taking ownership of this?

**Comment by tomdwadsa** [comment]
I hope I can help with this, I also have the problem (obviously), I tried to follow the steps, I first tried to delete tiny-dfr, but was told it was not installed, I restarted anyways, just to be extra shore.  After the restart I did the first line that AdityaGarg8 gave, then right after the second line? I was unsure how to handle the " after resume" so I skipped it. The first line closed the touchbar, as I supposed willingly (I am sorry, I am new to linux) and the second Line opened it again. And lastly I tried to go to sleep, wait half a minute and open again.  The Touchbar did not open itself unfortunatly,

**Comment by AdityaGarg8** [comment]
> I hope I can help with this, I also have the problem (obviously), I tried to follow the steps, I first tried to delete tiny-dfr, but was told it was not installed, I restarted anyways, just to be extra shore. After the restart I did the first line that AdityaGarg8 gave, then right after the second line? I was unsure how to handle the " after resume" so I skipped it. The first line closed the touchbar, as I supposed willingly (I am sorry, I am new to linux) and the second Line opened it again. And lastly I tried to go to sleep, wait half a minute and open again. The Touchbar did not open itself unfortunatly,

You are supposed to run the first line BEFORE GOING TO SLEEP and second line AFTER RESUMING FROM SLEEP.

**Comment by tomdwadsa** [comment]
I am sorry.
I did just that now, and afer the first line the touchbar went dark, after suspend and resuming the touchbar did apear and everything worked, exept the keyboard light brighter key, the keyboard light dim key funnily enough did work.
After the second line nothing that I noticed changed.

**Comment by AdityaGarg8** [comment]
> I am sorry. I did just that now, and afer the first line the touchbar went dark, after suspend and resuming the touchbar did apear and everything worked, exept the keyboard light brighter key, the keyboard light dim key funnily enough did work. After the second line nothing that I noticed changed.

Run `sudo systemctl restart upower` to fix the keyboard backlight key.

**Comment by AdityaGarg8** [comment]
Also, you don't need to run the command supposed to be run after resume if the touchbar comes back automatically.

**Comment by speroe** [comment]
I can reproduce a related current failure on a 2018 15-inch Intel T2 MacBook Pro A1990 (Radeon Pro 555X), Debian Trixie, linux-t2 7.1.2-1-t2-trixie.

Configuration:
- using the native Touch Bar mode (i.e. not tiny-dfr)
- `hid_appletb_kbd mode=1`
- Intel forced as display GPU; `amdgpu` blacklisted due to a separate AMD resume failure
- built-in keyboard, trackpad, and display recover normally after suspend

Before suspend, the native Touch Bar works.

After suspend/resume on 7.1.2:
- Touch Bar is completely dark / unusable.
- The log shows `hid-appletb-kbd` registering before the backlight device:
   `hid-appletb-kbd ... error -ENODEV: Failed to get backlight device`
- Once `hid-appletb-bl` appears, `hid-appletb-kbd` repeatedly logs:
   `usb_submit_urb(ctrl) failed: -1`
   `bce-vhci: [00] Unexpected transfer queue event`
- Reloading only `hid_appletb_kbd` after resume recreates the input device but does not restore the Touch Bar.

On 6.18.37-1-t2-trixie, native mode was slightly different: the bar displayed and Fn toggled its mode after resume, but it emitted no key events. With tiny-dfr, `appletbdrm` instead failed its post-resume probe with `-110`.

I also tested unloading `hid_appletb_kbd` and `hid_appletb_bl` before suspend and reloading after resume, but it did not restore working input.

Is there a known regression or recommended fix/order for current T2 firmware and kernel 7.1.2 on the 2018 15-inch models?

It seems like the same issue is reported here: https://github.com/t2linux/T2-Debian-and-Ubuntu-Kernel/issues/192#issue-4623091528
